FROM nginx:1.20-alpine
# https://hub.docker.com/_/nginx
# https://charlie1012.hatenablog.jp/entry/2021/01/14/090000

ENV TZ Asia/Tokyo

COPY ./infra/docker/web/default.conf /etc/nginx/conf.d/default.conf
