name: Run Laravel Test

on:
  pull_request:
    types: synchronize

jobs:
  run-laravel-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ubuntu Version
        run: cat /etc/os-release

      - name: Docker Version
        run: docker version

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ./api/vendor
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Docker Compose Build and Up
        run: |
          docker-compose build
          docker-compose up -d

      - name: Docker Compose Process
        run: docker-compose ps -a

      - name: PHP, Composer Version
        run: |
          docker-compose exec -T app php --version
          docker-compose exec -T app composer --version

      - name: Laravel Settings
        run: |
          docker-compose exec app composer install
          docker-compose exec app cp .env.example .env
          docker-compose exec app php artisan key:generate
          docker-compose exec app php artisan storage:link

      - name: Laravel Version
        run: docker-compose exec -T app php artisan --version

      - name: Laravel Migrate Testing
        run: docker-compose exec -T app php artisan migrate

      - name: Laravel Rollback Testing
        run: docker-compose exec -T app php artisan migrate:refresh

      - name: Laravel Seeding Testing
        run: docker-compose exec -T app php artisan db:seed

      - name: Laravel PHPUnit Testing
        run: |
          docker-compose exec -T app php artisan config:clear
          docker compose exec -T app php artisan test --parallel
